header:
  license:
    spdx-id: BSD-3-Clause-LBNL
    copyright-year: 2023
    software-name: MACIS 

  paths-ignore:
    - .github/
    - attic/
    - tests/ref_data/
    - LICENSE.txt
    - src/lobpcgxx/
    - src/sparsexx/tests/*.{mtx,rb}

  comment: never
